### ISSUE TITLE
Not working anymore with python-coverage version 7 or newer

### ISSUE THREAD

**Issue by actionless** [TheKevJames/coveralls-python#394]
```
E           ImportError: cannot import name 'Reporter' from 'coverage.report' (/usr/lib/python3.11/site-packages/coverage/report.py)

coveralls/reporter.py:122: ImportError

E       ImportError: cannot import name 'FnmatchMatcher' from 'coverage.files' (/usr/lib/python3.11/site-packages/coverage/files.py)

coveralls/reporter.py:64: ImportError
 ```
 
 with version 6.5.0 it still working

**Comment by actionless** [comment]
thanks! can confirm it works with 7.4.1 👍
